#!/bin/bash

docker-compose down

cd ..
mvn clean install -DskipTests
cp target/notificacion-0.0.1-SNAPSHOT.jar docker/

docker network create simit_network

cd docker
docker-compose up -d --build --scale simit-notifications=2
